link:
  railshome: "http://www.rubyonrails.org"
  railsbook: "http://www.railstutorial.org/book"
  contact: "https://www.railstutorial.org/contact"
  gravatar: "http://gravatar.com/emails"

validate:
  name: 
    length:
      max: 20
  email:
    length:
      max: 255
    regex: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  password:
    length:
      min: 6
  content:
    length:
      max: 140
  im:
    type: <%= %w(image/jpeg image/gif image/png) %>
    size: 50

size:
  gravatar: 80
  micropost: 50

pagy:
  user:
    items: 10
  micropost:
    items: 10

expired_time: 2
